
# db props
spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  # Enabling H2 Console
  h2:
    console:
      enabled: true
#  sql:
#    init:
#      data-locations: classpath:mock-sources/db/products.sql

logging:
  level:
    com.eshop: debug
